IF (EXISTS (SELECT COUNT(1) FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'Languages'))
DROP TABLE Languages
GO

CREATE TABLE [dbo].[Languages](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Code] [nvarchar](50) NOT NULL,
	[Value] [nvarchar](100) NOT NULL,
 CONSTRAINT [PK_Languages] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

INSERT INTO Languages (Code, Value) VALUES ('ab', 'Abkhazian');
INSERT INTO Languages (Code, Value) VALUES ('ace', 'Achinese');
INSERT INTO Languages (Code, Value) VALUES ('ach', 'Acoli');
INSERT INTO Languages (Code, Value) VALUES ('ada', 'Adangme');
INSERT INTO Languages (Code, Value) VALUES ('ady', 'Adyghe');
INSERT INTO Languages (Code, Value) VALUES ('aa', 'Afar');
INSERT INTO Languages (Code, Value) VALUES ('afh', 'Afrihili');
INSERT INTO Languages (Code, Value) VALUES ('af', 'Afrikaans');
INSERT INTO Languages (Code, Value) VALUES ('agq', 'Aghem');
INSERT INTO Languages (Code, Value) VALUES ('ain', 'Ainu');
INSERT INTO Languages (Code, Value) VALUES ('ak', 'Akan');
INSERT INTO Languages (Code, Value) VALUES ('akk', 'Akkadian');
INSERT INTO Languages (Code, Value) VALUES ('bss', 'Akoose');
INSERT INTO Languages (Code, Value) VALUES ('akz', 'Alabama');
INSERT INTO Languages (Code, Value) VALUES ('sq', 'Albanian');
INSERT INTO Languages (Code, Value) VALUES ('ale', 'Aleut');
INSERT INTO Languages (Code, Value) VALUES ('arq', 'Algerian Arabic');
INSERT INTO Languages (Code, Value) VALUES ('en_US', 'American English');
INSERT INTO Languages (Code, Value) VALUES ('ase', 'American Sign Language');
INSERT INTO Languages (Code, Value) VALUES ('am', 'Amharic');
INSERT INTO Languages (Code, Value) VALUES ('egy', 'Ancient Egyptian');
INSERT INTO Languages (Code, Value) VALUES ('grc', 'Ancient Greek');
INSERT INTO Languages (Code, Value) VALUES ('anp', 'Angika');
INSERT INTO Languages (Code, Value) VALUES ('njo', 'Ao Naga');
INSERT INTO Languages (Code, Value) VALUES ('ar', 'Arabic');
INSERT INTO Languages (Code, Value) VALUES ('an', 'Aragonese');
INSERT INTO Languages (Code, Value) VALUES ('arc', 'Aramaic');
INSERT INTO Languages (Code, Value) VALUES ('aro', 'Araona');
INSERT INTO Languages (Code, Value) VALUES ('arp', 'Arapaho');
INSERT INTO Languages (Code, Value) VALUES ('arw', 'Arawak');
INSERT INTO Languages (Code, Value) VALUES ('hy', 'Armenian');
INSERT INTO Languages (Code, Value) VALUES ('rup', 'Aromanian');
INSERT INTO Languages (Code, Value) VALUES ('frp', 'Arpitan');
INSERT INTO Languages (Code, Value) VALUES ('as', 'Assamese');
INSERT INTO Languages (Code, Value) VALUES ('ast', 'Asturian');
INSERT INTO Languages (Code, Value) VALUES ('asa', 'Asu');
INSERT INTO Languages (Code, Value) VALUES ('cch', 'Atsam');
INSERT INTO Languages (Code, Value) VALUES ('en_AU', 'Australian English');
INSERT INTO Languages (Code, Value) VALUES ('de_AT', 'Austrian German');
INSERT INTO Languages (Code, Value) VALUES ('av', 'Avaric');
INSERT INTO Languages (Code, Value) VALUES ('ae', 'Avestan');
INSERT INTO Languages (Code, Value) VALUES ('awa', 'Awadhi');
INSERT INTO Languages (Code, Value) VALUES ('ay', 'Aymara');
INSERT INTO Languages (Code, Value) VALUES ('az', 'Azerbaijani');
INSERT INTO Languages (Code, Value) VALUES ('bfq', 'Badaga');
INSERT INTO Languages (Code, Value) VALUES ('ksf', 'Bafia');
INSERT INTO Languages (Code, Value) VALUES ('bfd', 'Bafut');
INSERT INTO Languages (Code, Value) VALUES ('bqi', 'Bakhtiari');
INSERT INTO Languages (Code, Value) VALUES ('ban', 'Balinese');
INSERT INTO Languages (Code, Value) VALUES ('bal', 'Baluchi');
INSERT INTO Languages (Code, Value) VALUES ('bm', 'Bambara');
INSERT INTO Languages (Code, Value) VALUES ('bax', 'Bamun');
INSERT INTO Languages (Code, Value) VALUES ('bjn', 'Banjar');
INSERT INTO Languages (Code, Value) VALUES ('bas', 'Basaa');
INSERT INTO Languages (Code, Value) VALUES ('ba', 'Bashkir');
INSERT INTO Languages (Code, Value) VALUES ('eu', 'Basque');
INSERT INTO Languages (Code, Value) VALUES ('bbc', 'Batak Toba');
INSERT INTO Languages (Code, Value) VALUES ('bar', 'Bavarian');
INSERT INTO Languages (Code, Value) VALUES ('bej', 'Beja');
INSERT INTO Languages (Code, Value) VALUES ('be', 'Belarusian');
INSERT INTO Languages (Code, Value) VALUES ('bem', 'Bemba');
INSERT INTO Languages (Code, Value) VALUES ('bez', 'Bena');
INSERT INTO Languages (Code, Value) VALUES ('bn', 'Bengali');
INSERT INTO Languages (Code, Value) VALUES ('bew', 'Betawi');
INSERT INTO Languages (Code, Value) VALUES ('bho', 'Bhojpuri');
INSERT INTO Languages (Code, Value) VALUES ('bik', 'Bikol');
INSERT INTO Languages (Code, Value) VALUES ('bin', 'Bini');
INSERT INTO Languages (Code, Value) VALUES ('bpy', 'Bishnupriya');
INSERT INTO Languages (Code, Value) VALUES ('bi', 'Bislama');
INSERT INTO Languages (Code, Value) VALUES ('byn', 'Blin');
INSERT INTO Languages (Code, Value) VALUES ('zbl', 'Blissymbols');
INSERT INTO Languages (Code, Value) VALUES ('brx', 'Bodo');
INSERT INTO Languages (Code, Value) VALUES ('bs', 'Bosnian');
INSERT INTO Languages (Code, Value) VALUES ('brh', 'Brahui');
INSERT INTO Languages (Code, Value) VALUES ('bra', 'Braj');
INSERT INTO Languages (Code, Value) VALUES ('pt_BR', 'Brazilian Portuguese');
INSERT INTO Languages (Code, Value) VALUES ('br', 'Breton');
INSERT INTO Languages (Code, Value) VALUES ('en_GB', 'British English');
INSERT INTO Languages (Code, Value) VALUES ('bug', 'Buginese');
INSERT INTO Languages (Code, Value) VALUES ('bg', 'Bulgarian');
INSERT INTO Languages (Code, Value) VALUES ('bum', 'Bulu');
INSERT INTO Languages (Code, Value) VALUES ('bua', 'Buriat');
INSERT INTO Languages (Code, Value) VALUES ('my', 'Burmese');
INSERT INTO Languages (Code, Value) VALUES ('cad', 'Caddo');
INSERT INTO Languages (Code, Value) VALUES ('frc', 'Cajun French');
INSERT INTO Languages (Code, Value) VALUES ('en_CA', 'Canadian English');
INSERT INTO Languages (Code, Value) VALUES ('fr_CA', 'Canadian French');
INSERT INTO Languages (Code, Value) VALUES ('yue', 'Cantonese');
INSERT INTO Languages (Code, Value) VALUES ('cps', 'Capiznon');
INSERT INTO Languages (Code, Value) VALUES ('car', 'Carib');
INSERT INTO Languages (Code, Value) VALUES ('ca', 'Catalan');
INSERT INTO Languages (Code, Value) VALUES ('cay', 'Cayuga');
INSERT INTO Languages (Code, Value) VALUES ('ceb', 'Cebuano');
INSERT INTO Languages (Code, Value) VALUES ('tzm', 'Central Atlas Tamazight');
INSERT INTO Languages (Code, Value) VALUES ('dtp', 'Central Dusun');
INSERT INTO Languages (Code, Value) VALUES ('ckb', 'Central Kurdish');
INSERT INTO Languages (Code, Value) VALUES ('esu', 'Central Yupik');
INSERT INTO Languages (Code, Value) VALUES ('shu', 'Chadian Arabic');
INSERT INTO Languages (Code, Value) VALUES ('chg', 'Chagatai');
INSERT INTO Languages (Code, Value) VALUES ('ch', 'Chamorro');
INSERT INTO Languages (Code, Value) VALUES ('ce', 'Chechen');
INSERT INTO Languages (Code, Value) VALUES ('chr', 'Cherokee');
INSERT INTO Languages (Code, Value) VALUES ('chy', 'Cheyenne');
INSERT INTO Languages (Code, Value) VALUES ('chb', 'Chibcha');
INSERT INTO Languages (Code, Value) VALUES ('cgg', 'Chiga');
INSERT INTO Languages (Code, Value) VALUES ('qug', 'Chimborazo Highland Quichua');
INSERT INTO Languages (Code, Value) VALUES ('zh', 'Chinese');
INSERT INTO Languages (Code, Value) VALUES ('chn', 'Chinook Jargon');
INSERT INTO Languages (Code, Value) VALUES ('chp', 'Chipewyan');
INSERT INTO Languages (Code, Value) VALUES ('cho', 'Choctaw');
INSERT INTO Languages (Code, Value) VALUES ('cu', 'Church Slavic');
INSERT INTO Languages (Code, Value) VALUES ('chk', 'Chuukese');
INSERT INTO Languages (Code, Value) VALUES ('cv', 'Chuvash');
INSERT INTO Languages (Code, Value) VALUES ('nwc', 'Classical Newari');
INSERT INTO Languages (Code, Value) VALUES ('syc', 'Classical Syriac');
INSERT INTO Languages (Code, Value) VALUES ('ksh', 'Colognian');
INSERT INTO Languages (Code, Value) VALUES ('swb', 'Comorian');
INSERT INTO Languages (Code, Value) VALUES ('swc', 'Congo Swahili');
INSERT INTO Languages (Code, Value) VALUES ('cop', 'Coptic');
INSERT INTO Languages (Code, Value) VALUES ('kw', 'Cornish');
INSERT INTO Languages (Code, Value) VALUES ('co', 'Corsican');
INSERT INTO Languages (Code, Value) VALUES ('cr', 'Cree');
INSERT INTO Languages (Code, Value) VALUES ('mus', 'Creek');
INSERT INTO Languages (Code, Value) VALUES ('crh', 'Crimean Turkish');
INSERT INTO Languages (Code, Value) VALUES ('hr', 'Croatian');
INSERT INTO Languages (Code, Value) VALUES ('cs', 'Czech');
INSERT INTO Languages (Code, Value) VALUES ('dak', 'Dakota');
INSERT INTO Languages (Code, Value) VALUES ('da', 'Danish');
INSERT INTO Languages (Code, Value) VALUES ('dar', 'Dargwa');
INSERT INTO Languages (Code, Value) VALUES ('dzg', 'Dazaga');
INSERT INTO Languages (Code, Value) VALUES ('del', 'Delaware');
INSERT INTO Languages (Code, Value) VALUES ('din', 'Dinka');
INSERT INTO Languages (Code, Value) VALUES ('dv', 'Divehi');
INSERT INTO Languages (Code, Value) VALUES ('doi', 'Dogri');
INSERT INTO Languages (Code, Value) VALUES ('dgr', 'Dogrib');
INSERT INTO Languages (Code, Value) VALUES ('dua', 'Duala');
INSERT INTO Languages (Code, Value) VALUES ('nl', 'Dutch');
INSERT INTO Languages (Code, Value) VALUES ('dyu', 'Dyula');
INSERT INTO Languages (Code, Value) VALUES ('dz', 'Dzongkha');
INSERT INTO Languages (Code, Value) VALUES ('frs', 'Eastern Frisian');
INSERT INTO Languages (Code, Value) VALUES ('efi', 'Efik');
INSERT INTO Languages (Code, Value) VALUES ('arz', 'Egyptian Arabic');
INSERT INTO Languages (Code, Value) VALUES ('eka', 'Ekajuk');
INSERT INTO Languages (Code, Value) VALUES ('elx', 'Elamite');
INSERT INTO Languages (Code, Value) VALUES ('ebu', 'Embu');
INSERT INTO Languages (Code, Value) VALUES ('egl', 'Emilian');
INSERT INTO Languages (Code, Value) VALUES ('en', 'English');
INSERT INTO Languages (Code, Value) VALUES ('myv', 'Erzya');
INSERT INTO Languages (Code, Value) VALUES ('eo', 'Esperanto');
INSERT INTO Languages (Code, Value) VALUES ('et', 'Estonian');
INSERT INTO Languages (Code, Value) VALUES ('pt_PT', 'European Portuguese');
INSERT INTO Languages (Code, Value) VALUES ('es_ES', 'European Spanish');
INSERT INTO Languages (Code, Value) VALUES ('ee', 'Ewe');
INSERT INTO Languages (Code, Value) VALUES ('ewo', 'Ewondo');
INSERT INTO Languages (Code, Value) VALUES ('ext', 'Extremaduran');
INSERT INTO Languages (Code, Value) VALUES ('fan', 'Fang');
INSERT INTO Languages (Code, Value) VALUES ('fat', 'Fanti');
INSERT INTO Languages (Code, Value) VALUES ('fo', 'Faroese');
INSERT INTO Languages (Code, Value) VALUES ('hif', 'Fiji Hindi');
INSERT INTO Languages (Code, Value) VALUES ('fj', 'Fijian');
INSERT INTO Languages (Code, Value) VALUES ('fil', 'Filipino');
INSERT INTO Languages (Code, Value) VALUES ('fi', 'Finnish');
INSERT INTO Languages (Code, Value) VALUES ('nl_BE', 'Flemish');
INSERT INTO Languages (Code, Value) VALUES ('fon', 'Fon');
INSERT INTO Languages (Code, Value) VALUES ('gur', 'Frafra');
INSERT INTO Languages (Code, Value) VALUES ('fr', 'French');
INSERT INTO Languages (Code, Value) VALUES ('fur', 'Friulian');
INSERT INTO Languages (Code, Value) VALUES ('ff', 'Fulah');
INSERT INTO Languages (Code, Value) VALUES ('gaa', 'Ga');
INSERT INTO Languages (Code, Value) VALUES ('gag', 'Gagauz');
INSERT INTO Languages (Code, Value) VALUES ('gl', 'Galician');
INSERT INTO Languages (Code, Value) VALUES ('gan', 'Gan Chinese');
INSERT INTO Languages (Code, Value) VALUES ('lg', 'Ganda');
INSERT INTO Languages (Code, Value) VALUES ('gay', 'Gayo');
INSERT INTO Languages (Code, Value) VALUES ('gba', 'Gbaya');
INSERT INTO Languages (Code, Value) VALUES ('gez', 'Geez');
INSERT INTO Languages (Code, Value) VALUES ('ka', 'Georgian');
INSERT INTO Languages (Code, Value) VALUES ('de', 'German');
INSERT INTO Languages (Code, Value) VALUES ('aln', 'Gheg Albanian');
INSERT INTO Languages (Code, Value) VALUES ('bbj', 'Ghomala');
INSERT INTO Languages (Code, Value) VALUES ('glk', 'Gilaki');
INSERT INTO Languages (Code, Value) VALUES ('gil', 'Gilbertese');
INSERT INTO Languages (Code, Value) VALUES ('gom', 'Goan Konkani');
INSERT INTO Languages (Code, Value) VALUES ('gon', 'Gondi');
INSERT INTO Languages (Code, Value) VALUES ('gor', 'Gorontalo');
INSERT INTO Languages (Code, Value) VALUES ('got', 'Gothic');
INSERT INTO Languages (Code, Value) VALUES ('grb', 'Grebo');
INSERT INTO Languages (Code, Value) VALUES ('el', 'Greek');
INSERT INTO Languages (Code, Value) VALUES ('gn', 'Guarani');
INSERT INTO Languages (Code, Value) VALUES ('gu', 'Gujarati');
INSERT INTO Languages (Code, Value) VALUES ('guz', 'Gusii');
INSERT INTO Languages (Code, Value) VALUES ('gwi', 'Gwichʼin');
INSERT INTO Languages (Code, Value) VALUES ('hai', 'HaCodea');
INSERT INTO Languages (Code, Value) VALUES ('ht', 'Haitian');
INSERT INTO Languages (Code, Value) VALUES ('hak', 'Hakka Chinese');
INSERT INTO Languages (Code, Value) VALUES ('ha', 'Hausa');
INSERT INTO Languages (Code, Value) VALUES ('haw', 'Hawaiian');
INSERT INTO Languages (Code, Value) VALUES ('he', 'Hebrew');
INSERT INTO Languages (Code, Value) VALUES ('hz', 'Herero');
INSERT INTO Languages (Code, Value) VALUES ('hil', 'Hiligaynon');
INSERT INTO Languages (Code, Value) VALUES ('hi', 'Hindi');
INSERT INTO Languages (Code, Value) VALUES ('ho', 'Hiri Motu');
INSERT INTO Languages (Code, Value) VALUES ('hit', 'Hittite');
INSERT INTO Languages (Code, Value) VALUES ('hmn', 'Hmong');
INSERT INTO Languages (Code, Value) VALUES ('hu', 'Hungarian');
INSERT INTO Languages (Code, Value) VALUES ('hup', 'Hupa');
INSERT INTO Languages (Code, Value) VALUES ('iba', 'Iban');
INSERT INTO Languages (Code, Value) VALUES ('ibb', 'Ibibio');
INSERT INTO Languages (Code, Value) VALUES ('is', 'Icelandic');
INSERT INTO Languages (Code, Value) VALUES ('io', 'Codeo');
INSERT INTO Languages (Code, Value) VALUES ('ig', 'Igbo');
INSERT INTO Languages (Code, Value) VALUES ('ilo', 'Iloko');
INSERT INTO Languages (Code, Value) VALUES ('smn', 'Inari Sami');
INSERT INTO Languages (Code, Value) VALUES ('Code', 'Indonesian');
INSERT INTO Languages (Code, Value) VALUES ('izh', 'Ingrian');
INSERT INTO Languages (Code, Value) VALUES ('inh', 'Ingush');
INSERT INTO Languages (Code, Value) VALUES ('ia', 'Interlingua');
INSERT INTO Languages (Code, Value) VALUES ('ie', 'Interlingue');
INSERT INTO Languages (Code, Value) VALUES ('iu', 'Inuktitut');
INSERT INTO Languages (Code, Value) VALUES ('ik', 'Inupiaq');
INSERT INTO Languages (Code, Value) VALUES ('ga', 'Irish');
INSERT INTO Languages (Code, Value) VALUES ('it', 'Italian');
INSERT INTO Languages (Code, Value) VALUES ('jam', 'Jamaican Creole English');
INSERT INTO Languages (Code, Value) VALUES ('ja', 'Japanese');
INSERT INTO Languages (Code, Value) VALUES ('jv', 'Javanese');
INSERT INTO Languages (Code, Value) VALUES ('kaj', 'Jju');
INSERT INTO Languages (Code, Value) VALUES ('dyo', 'Jola-Fonyi');
INSERT INTO Languages (Code, Value) VALUES ('jrb', 'Judeo-Arabic');
INSERT INTO Languages (Code, Value) VALUES ('jpr', 'Judeo-Persian');
INSERT INTO Languages (Code, Value) VALUES ('jut', 'Jutish');
INSERT INTO Languages (Code, Value) VALUES ('kbd', 'Kabardian');
INSERT INTO Languages (Code, Value) VALUES ('kea', 'Kabuverdianu');
INSERT INTO Languages (Code, Value) VALUES ('kab', 'Kabyle');
INSERT INTO Languages (Code, Value) VALUES ('kac', 'Kachin');
INSERT INTO Languages (Code, Value) VALUES ('kgp', 'Kaingang');
INSERT INTO Languages (Code, Value) VALUES ('kkj', 'Kako');
INSERT INTO Languages (Code, Value) VALUES ('kl', 'Kalaallisut');
INSERT INTO Languages (Code, Value) VALUES ('kln', 'Kalenjin');
INSERT INTO Languages (Code, Value) VALUES ('xal', 'Kalmyk');
INSERT INTO Languages (Code, Value) VALUES ('kam', 'Kamba');
INSERT INTO Languages (Code, Value) VALUES ('kbl', 'Kanembu');
INSERT INTO Languages (Code, Value) VALUES ('kn', 'Kannada');
INSERT INTO Languages (Code, Value) VALUES ('kr', 'Kanuri');
INSERT INTO Languages (Code, Value) VALUES ('kaa', 'Kara-Kalpak');
INSERT INTO Languages (Code, Value) VALUES ('krc', 'Karachay-Balkar');
INSERT INTO Languages (Code, Value) VALUES ('krl', 'Karelian');
INSERT INTO Languages (Code, Value) VALUES ('ks', 'Kashmiri');
INSERT INTO Languages (Code, Value) VALUES ('csb', 'Kashubian');
INSERT INTO Languages (Code, Value) VALUES ('kaw', 'Kawi');
INSERT INTO Languages (Code, Value) VALUES ('kk', 'Kazakh');
INSERT INTO Languages (Code, Value) VALUES ('ken', 'Kenyang');
INSERT INTO Languages (Code, Value) VALUES ('kha', 'Khasi');
INSERT INTO Languages (Code, Value) VALUES ('km', 'Khmer');
INSERT INTO Languages (Code, Value) VALUES ('kho', 'Khotanese');
INSERT INTO Languages (Code, Value) VALUES ('khw', 'Khowar');
INSERT INTO Languages (Code, Value) VALUES ('ki', 'Kikuyu');
INSERT INTO Languages (Code, Value) VALUES ('kmb', 'Kimbundu');
INSERT INTO Languages (Code, Value) VALUES ('krj', 'Kinaray-a');
INSERT INTO Languages (Code, Value) VALUES ('rw', 'Kinyarwanda');
INSERT INTO Languages (Code, Value) VALUES ('kiu', 'Kirmanjki');
INSERT INTO Languages (Code, Value) VALUES ('tlh', 'Klingon');
INSERT INTO Languages (Code, Value) VALUES ('bkm', 'Kom');
INSERT INTO Languages (Code, Value) VALUES ('kv', 'Komi');
INSERT INTO Languages (Code, Value) VALUES ('koi', 'Komi-Permyak');
INSERT INTO Languages (Code, Value) VALUES ('kg', 'Kongo');
INSERT INTO Languages (Code, Value) VALUES ('kok', 'Konkani');
INSERT INTO Languages (Code, Value) VALUES ('ko', 'Korean');
INSERT INTO Languages (Code, Value) VALUES ('kfo', 'Koro');
INSERT INTO Languages (Code, Value) VALUES ('kos', 'Kosraean');
INSERT INTO Languages (Code, Value) VALUES ('avk', 'Kotava');
INSERT INTO Languages (Code, Value) VALUES ('khq', 'Koyra Chiini');
INSERT INTO Languages (Code, Value) VALUES ('ses', 'Koyraboro Senni');
INSERT INTO Languages (Code, Value) VALUES ('kpe', 'Kpelle');
INSERT INTO Languages (Code, Value) VALUES ('kri', 'Krio');
INSERT INTO Languages (Code, Value) VALUES ('kj', 'Kuanyama');
INSERT INTO Languages (Code, Value) VALUES ('kum', 'Kumyk');
INSERT INTO Languages (Code, Value) VALUES ('ku', 'Kurdish');
INSERT INTO Languages (Code, Value) VALUES ('kru', 'Kurukh');
INSERT INTO Languages (Code, Value) VALUES ('kut', 'Kutenai');
INSERT INTO Languages (Code, Value) VALUES ('nmg', 'Kwasio');
INSERT INTO Languages (Code, Value) VALUES ('ky', 'Kyrgyz');
INSERT INTO Languages (Code, Value) VALUES ('quc', 'Kʼicheʼ');
INSERT INTO Languages (Code, Value) VALUES ('lad', 'Ladino');
INSERT INTO Languages (Code, Value) VALUES ('lah', 'Lahnda');
INSERT INTO Languages (Code, Value) VALUES ('lkt', 'Lakota');
INSERT INTO Languages (Code, Value) VALUES ('lam', 'Lamba');
INSERT INTO Languages (Code, Value) VALUES ('lag', 'Langi');
INSERT INTO Languages (Code, Value) VALUES ('lo', 'Lao');
INSERT INTO Languages (Code, Value) VALUES ('ltg', 'Latgalian');
INSERT INTO Languages (Code, Value) VALUES ('la', 'Latin');
INSERT INTO Languages (Code, Value) VALUES ('es_419', 'Latin American Spanish');
INSERT INTO Languages (Code, Value) VALUES ('lv', 'Latvian');
INSERT INTO Languages (Code, Value) VALUES ('lzz', 'Laz');
INSERT INTO Languages (Code, Value) VALUES ('lez', 'Lezghian');
INSERT INTO Languages (Code, Value) VALUES ('lij', 'Ligurian');
INSERT INTO Languages (Code, Value) VALUES ('li', 'Limburgish');
INSERT INTO Languages (Code, Value) VALUES ('ln', 'Lingala');
INSERT INTO Languages (Code, Value) VALUES ('lfn', 'Lingua Franca Nova');
INSERT INTO Languages (Code, Value) VALUES ('lzh', 'Literary Chinese');
INSERT INTO Languages (Code, Value) VALUES ('lt', 'Lithuanian');
INSERT INTO Languages (Code, Value) VALUES ('liv', 'Livonian');
INSERT INTO Languages (Code, Value) VALUES ('jbo', 'Lojban');
INSERT INTO Languages (Code, Value) VALUES ('lmo', 'Lombard');
INSERT INTO Languages (Code, Value) VALUES ('nds', 'Low German');
INSERT INTO Languages (Code, Value) VALUES ('sli', 'Lower Silesian');
INSERT INTO Languages (Code, Value) VALUES ('dsb', 'Lower Sorbian');
INSERT INTO Languages (Code, Value) VALUES ('loz', 'Lozi');
INSERT INTO Languages (Code, Value) VALUES ('lu', 'Luba-Katanga');
INSERT INTO Languages (Code, Value) VALUES ('lua', 'Luba-Lulua');
INSERT INTO Languages (Code, Value) VALUES ('lui', 'Luiseno');
INSERT INTO Languages (Code, Value) VALUES ('smj', 'Lule Sami');
INSERT INTO Languages (Code, Value) VALUES ('lun', 'Lunda');
INSERT INTO Languages (Code, Value) VALUES ('luo', 'Luo');
INSERT INTO Languages (Code, Value) VALUES ('lb', 'Luxembourgish');
INSERT INTO Languages (Code, Value) VALUES ('luy', 'Luyia');
INSERT INTO Languages (Code, Value) VALUES ('mde', 'Maba');
INSERT INTO Languages (Code, Value) VALUES ('mk', 'Macedonian');
INSERT INTO Languages (Code, Value) VALUES ('jmc', 'Machame');
INSERT INTO Languages (Code, Value) VALUES ('mad', 'Madurese');
INSERT INTO Languages (Code, Value) VALUES ('maf', 'Mafa');
INSERT INTO Languages (Code, Value) VALUES ('mag', 'Magahi');
INSERT INTO Languages (Code, Value) VALUES ('vmf', 'Main-Franconian');
INSERT INTO Languages (Code, Value) VALUES ('mai', 'Maithili');
INSERT INTO Languages (Code, Value) VALUES ('mak', 'Makasar');
INSERT INTO Languages (Code, Value) VALUES ('mgh', 'Makhuwa-Meetto');
INSERT INTO Languages (Code, Value) VALUES ('kde', 'Makonde');
INSERT INTO Languages (Code, Value) VALUES ('mg', 'Malagasy');
INSERT INTO Languages (Code, Value) VALUES ('ms', 'Malay');
INSERT INTO Languages (Code, Value) VALUES ('ml', 'Malayalam');
INSERT INTO Languages (Code, Value) VALUES ('mt', 'Maltese');
INSERT INTO Languages (Code, Value) VALUES ('mnc', 'Manchu');
INSERT INTO Languages (Code, Value) VALUES ('mdr', 'Mandar');
INSERT INTO Languages (Code, Value) VALUES ('man', 'Mandingo');
INSERT INTO Languages (Code, Value) VALUES ('mni', 'Manipuri');
INSERT INTO Languages (Code, Value) VALUES ('gv', 'Manx');
INSERT INTO Languages (Code, Value) VALUES ('mi', 'Maori');
INSERT INTO Languages (Code, Value) VALUES ('arn', 'Mapuche');
INSERT INTO Languages (Code, Value) VALUES ('mr', 'Marathi');
INSERT INTO Languages (Code, Value) VALUES ('chm', 'Mari');
INSERT INTO Languages (Code, Value) VALUES ('mh', 'Marshallese');
INSERT INTO Languages (Code, Value) VALUES ('mwr', 'Marwari');
INSERT INTO Languages (Code, Value) VALUES ('mas', 'Masai');
INSERT INTO Languages (Code, Value) VALUES ('mzn', 'Mazanderani');
INSERT INTO Languages (Code, Value) VALUES ('byv', 'Medumba');
INSERT INTO Languages (Code, Value) VALUES ('men', 'Mende');
INSERT INTO Languages (Code, Value) VALUES ('mwv', 'Mentawai');
INSERT INTO Languages (Code, Value) VALUES ('mer', 'Meru');
INSERT INTO Languages (Code, Value) VALUES ('mgo', 'Metaʼ');
INSERT INTO Languages (Code, Value) VALUES ('es_MX', 'Mexican Spanish');
INSERT INTO Languages (Code, Value) VALUES ('mic', 'Micmac');
INSERT INTO Languages (Code, Value) VALUES ('dum', 'MCodedle Dutch');
INSERT INTO Languages (Code, Value) VALUES ('enm', 'MCodedle English');
INSERT INTO Languages (Code, Value) VALUES ('frm', 'MCodedle French');
INSERT INTO Languages (Code, Value) VALUES ('gmh', 'MCodedle High German');
INSERT INTO Languages (Code, Value) VALUES ('mga', 'MCodedle Irish');
INSERT INTO Languages (Code, Value) VALUES ('nan', 'Min Nan Chinese');
INSERT INTO Languages (Code, Value) VALUES ('min', 'Minangkabau');
INSERT INTO Languages (Code, Value) VALUES ('xmf', 'Mingrelian');
INSERT INTO Languages (Code, Value) VALUES ('mwl', 'Mirandese');
INSERT INTO Languages (Code, Value) VALUES ('lus', 'Mizo');
INSERT INTO Languages (Code, Value) VALUES ('ar_001', 'Modern Standard Arabic');
INSERT INTO Languages (Code, Value) VALUES ('moh', 'Mohawk');
INSERT INTO Languages (Code, Value) VALUES ('mdf', 'Moksha');
INSERT INTO Languages (Code, Value) VALUES ('ro_MD', 'Moldavian');
INSERT INTO Languages (Code, Value) VALUES ('lol', 'Mongo');
INSERT INTO Languages (Code, Value) VALUES ('mn', 'Mongolian');
INSERT INTO Languages (Code, Value) VALUES ('mfe', 'Morisyen');
INSERT INTO Languages (Code, Value) VALUES ('ary', 'Moroccan Arabic');
INSERT INTO Languages (Code, Value) VALUES ('mos', 'Mossi');
INSERT INTO Languages (Code, Value) VALUES ('mul', 'Multiple Languages');
INSERT INTO Languages (Code, Value) VALUES ('mua', 'Mundang');
INSERT INTO Languages (Code, Value) VALUES ('ttt', 'Muslim Tat');
INSERT INTO Languages (Code, Value) VALUES ('mye', 'Myene');
INSERT INTO Languages (Code, Value) VALUES ('naq', 'Nama');
INSERT INTO Languages (Code, Value) VALUES ('na', 'Nauru');
INSERT INTO Languages (Code, Value) VALUES ('nv', 'Navajo');
INSERT INTO Languages (Code, Value) VALUES ('ng', 'Ndonga');
INSERT INTO Languages (Code, Value) VALUES ('nap', 'Neapolitan');
INSERT INTO Languages (Code, Value) VALUES ('ne', 'Nepali');
INSERT INTO Languages (Code, Value) VALUES ('new', 'Newari');
INSERT INTO Languages (Code, Value) VALUES ('sba', 'Ngambay');
INSERT INTO Languages (Code, Value) VALUES ('nnh', 'Ngiemboon');
INSERT INTO Languages (Code, Value) VALUES ('jgo', 'Ngomba');
INSERT INTO Languages (Code, Value) VALUES ('yrl', 'Nheengatu');
INSERT INTO Languages (Code, Value) VALUES ('nia', 'Nias');
INSERT INTO Languages (Code, Value) VALUES ('niu', 'Niuean');
INSERT INTO Languages (Code, Value) VALUES ('zxx', 'No linguistic content');
INSERT INTO Languages (Code, Value) VALUES ('nog', 'Nogai');
INSERT INTO Languages (Code, Value) VALUES ('nd', 'North Ndebele');
INSERT INTO Languages (Code, Value) VALUES ('frr', 'Northern Frisian');
INSERT INTO Languages (Code, Value) VALUES ('se', 'Northern Sami');
INSERT INTO Languages (Code, Value) VALUES ('nso', 'Northern Sotho');
INSERT INTO Languages (Code, Value) VALUES ('no', 'Norwegian');
INSERT INTO Languages (Code, Value) VALUES ('nb', 'Norwegian Bokmål');
INSERT INTO Languages (Code, Value) VALUES ('nn', 'Norwegian Nynorsk');
INSERT INTO Languages (Code, Value) VALUES ('nov', 'Novial');
INSERT INTO Languages (Code, Value) VALUES ('nus', 'Nuer');
INSERT INTO Languages (Code, Value) VALUES ('nym', 'Nyamwezi');
INSERT INTO Languages (Code, Value) VALUES ('ny', 'Nyanja');
INSERT INTO Languages (Code, Value) VALUES ('nyn', 'Nyankole');
INSERT INTO Languages (Code, Value) VALUES ('tog', 'Nyasa Tonga');
INSERT INTO Languages (Code, Value) VALUES ('nyo', 'Nyoro');
INSERT INTO Languages (Code, Value) VALUES ('nzi', 'Nzima');
INSERT INTO Languages (Code, Value) VALUES ('nqo', 'NʼKo');
INSERT INTO Languages (Code, Value) VALUES ('oc', 'Occitan');
INSERT INTO Languages (Code, Value) VALUES ('oj', 'Ojibwa');
INSERT INTO Languages (Code, Value) VALUES ('ang', 'Old English');
INSERT INTO Languages (Code, Value) VALUES ('fro', 'Old French');
INSERT INTO Languages (Code, Value) VALUES ('goh', 'Old High German');
INSERT INTO Languages (Code, Value) VALUES ('sga', 'Old Irish');
INSERT INTO Languages (Code, Value) VALUES ('non', 'Old Norse');
INSERT INTO Languages (Code, Value) VALUES ('peo', 'Old Persian');
INSERT INTO Languages (Code, Value) VALUES ('pro', 'Old Provençal');
INSERT INTO Languages (Code, Value) VALUES ('or', 'Oriya');
INSERT INTO Languages (Code, Value) VALUES ('om', 'Oromo');
INSERT INTO Languages (Code, Value) VALUES ('osa', 'Osage');
INSERT INTO Languages (Code, Value) VALUES ('os', 'Ossetic');
INSERT INTO Languages (Code, Value) VALUES ('ota', 'Ottoman Turkish');
INSERT INTO Languages (Code, Value) VALUES ('pal', 'Pahlavi');
INSERT INTO Languages (Code, Value) VALUES ('pfl', 'Palatine German');
INSERT INTO Languages (Code, Value) VALUES ('pau', 'Palauan');
INSERT INTO Languages (Code, Value) VALUES ('pi', 'Pali');
INSERT INTO Languages (Code, Value) VALUES ('pam', 'Pampanga');
INSERT INTO Languages (Code, Value) VALUES ('pag', 'Pangasinan');
INSERT INTO Languages (Code, Value) VALUES ('pap', 'Papiamento');
INSERT INTO Languages (Code, Value) VALUES ('ps', 'Pashto');
INSERT INTO Languages (Code, Value) VALUES ('pdc', 'Pennsylvania German');
INSERT INTO Languages (Code, Value) VALUES ('fa', 'Persian');
INSERT INTO Languages (Code, Value) VALUES ('phn', 'Phoenician');
INSERT INTO Languages (Code, Value) VALUES ('pcd', 'Picard');
INSERT INTO Languages (Code, Value) VALUES ('pms', 'Piedmontese');
INSERT INTO Languages (Code, Value) VALUES ('pdt', 'Plautdietsch');
INSERT INTO Languages (Code, Value) VALUES ('pon', 'Pohnpeian');
INSERT INTO Languages (Code, Value) VALUES ('pl', 'Polish');
INSERT INTO Languages (Code, Value) VALUES ('pnt', 'Pontic');
INSERT INTO Languages (Code, Value) VALUES ('pt', 'Portuguese');
INSERT INTO Languages (Code, Value) VALUES ('prg', 'Prussian');
INSERT INTO Languages (Code, Value) VALUES ('pa', 'Punjabi');
INSERT INTO Languages (Code, Value) VALUES ('qu', 'Quechua');
INSERT INTO Languages (Code, Value) VALUES ('raj', 'Rajasthani');
INSERT INTO Languages (Code, Value) VALUES ('rap', 'Rapanui');
INSERT INTO Languages (Code, Value) VALUES ('rar', 'Rarotongan');
INSERT INTO Languages (Code, Value) VALUES ('rif', 'Riffian');
INSERT INTO Languages (Code, Value) VALUES ('rgn', 'Romagnol');
INSERT INTO Languages (Code, Value) VALUES ('ro', 'Romanian');
INSERT INTO Languages (Code, Value) VALUES ('rm', 'Romansh');
INSERT INTO Languages (Code, Value) VALUES ('rom', 'Romany');
INSERT INTO Languages (Code, Value) VALUES ('rof', 'Rombo');
INSERT INTO Languages (Code, Value) VALUES ('root', 'Root');
INSERT INTO Languages (Code, Value) VALUES ('rtm', 'Rotuman');
INSERT INTO Languages (Code, Value) VALUES ('rug', 'Roviana');
INSERT INTO Languages (Code, Value) VALUES ('rn', 'Rundi');
INSERT INTO Languages (Code, Value) VALUES ('ru', 'Russian');
INSERT INTO Languages (Code, Value) VALUES ('rue', 'Rusyn');
INSERT INTO Languages (Code, Value) VALUES ('rwk', 'Rwa');
INSERT INTO Languages (Code, Value) VALUES ('ssy', 'Saho');
INSERT INTO Languages (Code, Value) VALUES ('sah', 'Sakha');
INSERT INTO Languages (Code, Value) VALUES ('sam', 'Samaritan Aramaic');
INSERT INTO Languages (Code, Value) VALUES ('saq', 'Samburu');
INSERT INTO Languages (Code, Value) VALUES ('sm', 'Samoan');
INSERT INTO Languages (Code, Value) VALUES ('sgs', 'Samogitian');
INSERT INTO Languages (Code, Value) VALUES ('sad', 'Sandawe');
INSERT INTO Languages (Code, Value) VALUES ('sg', 'Sango');
INSERT INTO Languages (Code, Value) VALUES ('sbp', 'Sangu');
INSERT INTO Languages (Code, Value) VALUES ('sa', 'Sanskrit');
INSERT INTO Languages (Code, Value) VALUES ('sat', 'Santali');
INSERT INTO Languages (Code, Value) VALUES ('sc', 'Sardinian');
INSERT INTO Languages (Code, Value) VALUES ('sas', 'Sasak');
INSERT INTO Languages (Code, Value) VALUES ('sdc', 'Sassarese Sardinian');
INSERT INTO Languages (Code, Value) VALUES ('stq', 'Saterland Frisian');
INSERT INTO Languages (Code, Value) VALUES ('saz', 'Saurashtra');
INSERT INTO Languages (Code, Value) VALUES ('sco', 'Scots');
INSERT INTO Languages (Code, Value) VALUES ('gd', 'Scottish Gaelic');
INSERT INTO Languages (Code, Value) VALUES ('sly', 'Selayar');
INSERT INTO Languages (Code, Value) VALUES ('sel', 'Selkup');
INSERT INTO Languages (Code, Value) VALUES ('seh', 'Sena');
INSERT INTO Languages (Code, Value) VALUES ('see', 'Seneca');
INSERT INTO Languages (Code, Value) VALUES ('sr', 'Serbian');
INSERT INTO Languages (Code, Value) VALUES ('sh', 'Serbo-Croatian');
INSERT INTO Languages (Code, Value) VALUES ('srr', 'Serer');
INSERT INTO Languages (Code, Value) VALUES ('sei', 'Seri');
INSERT INTO Languages (Code, Value) VALUES ('ksb', 'Shambala');
INSERT INTO Languages (Code, Value) VALUES ('shn', 'Shan');
INSERT INTO Languages (Code, Value) VALUES ('sn', 'Shona');
INSERT INTO Languages (Code, Value) VALUES ('ii', 'Sichuan Yi');
INSERT INTO Languages (Code, Value) VALUES ('scn', 'Sicilian');
INSERT INTO Languages (Code, Value) VALUES ('sCode', 'SCodeamo');
INSERT INTO Languages (Code, Value) VALUES ('bla', 'Siksika');
INSERT INTO Languages (Code, Value) VALUES ('szl', 'Silesian');
INSERT INTO Languages (Code, Value) VALUES ('zh_Hans', 'Simplified Chinese');
INSERT INTO Languages (Code, Value) VALUES ('sd', 'Sindhi');
INSERT INTO Languages (Code, Value) VALUES ('si', 'Sinhala');
INSERT INTO Languages (Code, Value) VALUES ('sms', 'Skolt Sami');
INSERT INTO Languages (Code, Value) VALUES ('den', 'Slave');
INSERT INTO Languages (Code, Value) VALUES ('sk', 'Slovak');
INSERT INTO Languages (Code, Value) VALUES ('sl', 'Slovenian');
INSERT INTO Languages (Code, Value) VALUES ('xog', 'Soga');
INSERT INTO Languages (Code, Value) VALUES ('sog', 'Sogdien');
INSERT INTO Languages (Code, Value) VALUES ('so', 'Somali');
INSERT INTO Languages (Code, Value) VALUES ('snk', 'Soninke');
INSERT INTO Languages (Code, Value) VALUES ('azb', 'South Azerbaijani');
INSERT INTO Languages (Code, Value) VALUES ('nr', 'South Ndebele');
INSERT INTO Languages (Code, Value) VALUES ('alt', 'Southern Altai');
INSERT INTO Languages (Code, Value) VALUES ('sma', 'Southern Sami');
INSERT INTO Languages (Code, Value) VALUES ('st', 'Southern Sotho');
INSERT INTO Languages (Code, Value) VALUES ('es', 'Spanish');
INSERT INTO Languages (Code, Value) VALUES ('srn', 'Sranan Tongo');
INSERT INTO Languages (Code, Value) VALUES ('zgh', 'Standard Moroccan Tamazight');
INSERT INTO Languages (Code, Value) VALUES ('suk', 'Sukuma');
INSERT INTO Languages (Code, Value) VALUES ('sux', 'Sumerian');
INSERT INTO Languages (Code, Value) VALUES ('su', 'Sundanese');
INSERT INTO Languages (Code, Value) VALUES ('sus', 'Susu');
INSERT INTO Languages (Code, Value) VALUES ('sw', 'Swahili');
INSERT INTO Languages (Code, Value) VALUES ('ss', 'Swati');
INSERT INTO Languages (Code, Value) VALUES ('sv', 'Swedish');
INSERT INTO Languages (Code, Value) VALUES ('fr_CH', 'Swiss French');
INSERT INTO Languages (Code, Value) VALUES ('gsw', 'Swiss German');
INSERT INTO Languages (Code, Value) VALUES ('de_CH', 'Swiss High German');
INSERT INTO Languages (Code, Value) VALUES ('syr', 'Syriac');
INSERT INTO Languages (Code, Value) VALUES ('shi', 'Tachelhit');
INSERT INTO Languages (Code, Value) VALUES ('tl', 'Tagalog');
INSERT INTO Languages (Code, Value) VALUES ('ty', 'Tahitian');
INSERT INTO Languages (Code, Value) VALUES ('dav', 'Taita');
INSERT INTO Languages (Code, Value) VALUES ('tg', 'Tajik');
INSERT INTO Languages (Code, Value) VALUES ('tly', 'Talysh');
INSERT INTO Languages (Code, Value) VALUES ('tmh', 'Tamashek');
INSERT INTO Languages (Code, Value) VALUES ('ta', 'Tamil');
INSERT INTO Languages (Code, Value) VALUES ('trv', 'Taroko');
INSERT INTO Languages (Code, Value) VALUES ('twq', 'Tasawaq');
INSERT INTO Languages (Code, Value) VALUES ('tt', 'Tatar');
INSERT INTO Languages (Code, Value) VALUES ('te', 'Telugu');
INSERT INTO Languages (Code, Value) VALUES ('ter', 'Tereno');
INSERT INTO Languages (Code, Value) VALUES ('teo', 'Teso');
INSERT INTO Languages (Code, Value) VALUES ('tet', 'Tetum');
INSERT INTO Languages (Code, Value) VALUES ('th', 'Thai');
INSERT INTO Languages (Code, Value) VALUES ('bo', 'Tibetan');
INSERT INTO Languages (Code, Value) VALUES ('tig', 'Tigre');
INSERT INTO Languages (Code, Value) VALUES ('ti', 'Tigrinya');
INSERT INTO Languages (Code, Value) VALUES ('tem', 'Timne');
INSERT INTO Languages (Code, Value) VALUES ('tiv', 'Tiv');
INSERT INTO Languages (Code, Value) VALUES ('tli', 'Tlingit');
INSERT INTO Languages (Code, Value) VALUES ('tpi', 'Tok Pisin');
INSERT INTO Languages (Code, Value) VALUES ('tkl', 'Tokelau');
INSERT INTO Languages (Code, Value) VALUES ('to', 'Tongan');
INSERT INTO Languages (Code, Value) VALUES ('fit', 'Tornedalen Finnish');
INSERT INTO Languages (Code, Value) VALUES ('zh_Hant', 'Traditional Chinese');
INSERT INTO Languages (Code, Value) VALUES ('tkr', 'Tsakhur');
INSERT INTO Languages (Code, Value) VALUES ('tsd', 'Tsakonian');
INSERT INTO Languages (Code, Value) VALUES ('tsi', 'Tsimshian');
INSERT INTO Languages (Code, Value) VALUES ('ts', 'Tsonga');
INSERT INTO Languages (Code, Value) VALUES ('tn', 'Tswana');
INSERT INTO Languages (Code, Value) VALUES ('tcy', 'Tulu');
INSERT INTO Languages (Code, Value) VALUES ('tum', 'Tumbuka');
INSERT INTO Languages (Code, Value) VALUES ('aeb', 'Tunisian Arabic');
INSERT INTO Languages (Code, Value) VALUES ('tr', 'Turkish');
INSERT INTO Languages (Code, Value) VALUES ('tk', 'Turkmen');
INSERT INTO Languages (Code, Value) VALUES ('tru', 'Turoyo');
INSERT INTO Languages (Code, Value) VALUES ('tvl', 'Tuvalu');
INSERT INTO Languages (Code, Value) VALUES ('tyv', 'Tuvinian');
INSERT INTO Languages (Code, Value) VALUES ('tw', 'Twi');
INSERT INTO Languages (Code, Value) VALUES ('kcg', 'Tyap');
INSERT INTO Languages (Code, Value) VALUES ('udm', 'Udmurt');
INSERT INTO Languages (Code, Value) VALUES ('uga', 'Ugaritic');
INSERT INTO Languages (Code, Value) VALUES ('uk', 'Ukrainian');
INSERT INTO Languages (Code, Value) VALUES ('umb', 'Umbundu');
INSERT INTO Languages (Code, Value) VALUES ('und', 'Unknown Language');
INSERT INTO Languages (Code, Value) VALUES ('hsb', 'Upper Sorbian');
INSERT INTO Languages (Code, Value) VALUES ('ur', 'Urdu');
INSERT INTO Languages (Code, Value) VALUES ('ug', 'Uyghur');
INSERT INTO Languages (Code, Value) VALUES ('uz', 'Uzbek');
INSERT INTO Languages (Code, Value) VALUES ('vai', 'Vai');
INSERT INTO Languages (Code, Value) VALUES ('ve', 'Venda');
INSERT INTO Languages (Code, Value) VALUES ('vec', 'Venetian');
INSERT INTO Languages (Code, Value) VALUES ('vep', 'Veps');
INSERT INTO Languages (Code, Value) VALUES ('vi', 'Vietnamese');
INSERT INTO Languages (Code, Value) VALUES ('vo', 'Volapük');
INSERT INTO Languages (Code, Value) VALUES ('vro', 'Võro');
INSERT INTO Languages (Code, Value) VALUES ('vot', 'Votic');
INSERT INTO Languages (Code, Value) VALUES ('vun', 'Vunjo');
INSERT INTO Languages (Code, Value) VALUES ('wa', 'Walloon');
INSERT INTO Languages (Code, Value) VALUES ('wae', 'Walser');
INSERT INTO Languages (Code, Value) VALUES ('war', 'Waray');
INSERT INTO Languages (Code, Value) VALUES ('wbp', 'Warlpiri');
INSERT INTO Languages (Code, Value) VALUES ('was', 'Washo');
INSERT INTO Languages (Code, Value) VALUES ('guc', 'Wayuu');
INSERT INTO Languages (Code, Value) VALUES ('cy', 'Welsh');
INSERT INTO Languages (Code, Value) VALUES ('vls', 'West Flemish');
INSERT INTO Languages (Code, Value) VALUES ('fy', 'Western Frisian');
INSERT INTO Languages (Code, Value) VALUES ('mrj', 'Western Mari');
INSERT INTO Languages (Code, Value) VALUES ('wal', 'Wolaytta');
INSERT INTO Languages (Code, Value) VALUES ('wo', 'Wolof');
INSERT INTO Languages (Code, Value) VALUES ('wuu', 'Wu Chinese');
INSERT INTO Languages (Code, Value) VALUES ('xh', 'Xhosa');
INSERT INTO Languages (Code, Value) VALUES ('hsn', 'Xiang Chinese');
INSERT INTO Languages (Code, Value) VALUES ('yav', 'Yangben');
INSERT INTO Languages (Code, Value) VALUES ('yao', 'Yao');
INSERT INTO Languages (Code, Value) VALUES ('yap', 'Yapese');
INSERT INTO Languages (Code, Value) VALUES ('ybb', 'Yemba');
INSERT INTO Languages (Code, Value) VALUES ('yi', 'YCodedish');
INSERT INTO Languages (Code, Value) VALUES ('yo', 'Yoruba');
INSERT INTO Languages (Code, Value) VALUES ('zap', 'Zapotec');
INSERT INTO Languages (Code, Value) VALUES ('dje', 'Zarma');
INSERT INTO Languages (Code, Value) VALUES ('zza', 'Zaza');
INSERT INTO Languages (Code, Value) VALUES ('zea', 'Zeelandic');
INSERT INTO Languages (Code, Value) VALUES ('zen', 'Zenaga');
INSERT INTO Languages (Code, Value) VALUES ('za', 'Zhuang');
INSERT INTO Languages (Code, Value) VALUES ('gbz', 'Zoroastrian Dari');
INSERT INTO Languages (Code, Value) VALUES ('zu', 'Zulu');
INSERT INTO Languages (Code, Value) VALUES ('zun', 'Zuni');